### ISSUE TITLE
Update Font Awesome

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/prismlauncher.org#105]
It appears that the website is using v4 or v5 of Font Awesome, while v6.2.0 is the latest.

Updating Font Awesome shouldn't be too difficult or you can use your own kit from Font Awesome's website on your account.

Optionally, if you want, I can create a Font Awesome **Pro** kit for you to use, as I am paying $99/year for it to use on other websites and other company websites.

Font Awesome free kit for Prism to use:
```
<script src="https://kit.fontawesome.com/824ba5941f.js" crossorigin="anonymous"></script>
``` 

or

Font Awesome **Pro** kit for Prism to use: (Access to Pro icons and more styles)
```
<script src="https://kit.fontawesome.com/52f8d85e94.js" crossorigin="anonymous"></script>
```

Both kits provided are managed under my account.
But you can always sign up yourself and create your own kit.

**Comment by ZekeSmith** [comment]
The website doesnt use font awesome

**Comment by Scrumplex** [comment]
> The website doesnt use font awesome

The social icons use `fa` classes
