### ISSUE TITLE
Quilt support for Optifine

### ISSUE THREAD

**Issue by MacStevins** [PrismLauncher/prismlauncher.org#311]
In the "Installing Optifine" page of the wiki, it says on the "Quilt" section that, `There's no way of running OptiFine on Quilt`, when Quilt can run Fabric mods just fine, just use the same steps with Fabric.

Quilt Loader running with OptiFabric and OptiFine, Fabric API works just fine and sadly Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL) crashes, but the devs are currently creating support for the API

![image](https://github.com/PrismLauncher/prismlauncher.org/assets/15080111/9447a56f-3224-4830-a267-e038212fe3db)

**Comment by DioEgizio** [comment]
OptiFabric doesn't properly work with qfapi, which is the supposed way to run quilt. At that point there's no reason to use quilt and just use fabric tbh. Also the less people use optifine the better it is for mod devs tbh. I don't think that should be changed

**Comment by TheKodeToad** [comment]
I think encouraging using Quilt with Fabric API is not a good idea... you're probably not going to be able to run many Quilt mods that way.

**Comment by MacStevins** [comment]
> I think encouraging using Quilt with Fabric API is not a good idea... you're probably not going to be able to run many Quilt mods that way.

yeah fair

**Comment by MacStevins** [comment]
> OptiFabric doesn't properly work with qfapi, which is the supposed way to run quilt.

i was thinking that it would reflect that it _can_ work on Fabric API

**Comment by TheKodeToad** [comment]
Running OptiFine with a mod loader is also not really a good idea in the first place. I'm pretty sure OptiFine uses some hacks involving reflection to run on Forge and OptiFabric also uses some very dirty hacks.
