### ISSUE TITLE
Steam screenshots still PolyMC

### ISSUE THREAD

**Issue by ModProg** [PrismLauncher/prismlauncher.org#35]
Also we might add a reference to `https://www.steamgriddb.com/boop` which makes installing artwork a lot less cumbersome when using steamgriddb

**Comment by DBTDerpbox** [comment]
This also goes for the Windows and Mac screenshots on the download page, they're using PolyMC

**Comment by DBTDerpbox** [comment]
I might actually make a PR for this, as i've got access to both a windows PC and a mac, its an intel mac but nobody will notice from a screenshot

**Comment by Lutitious** [comment]
I will rewrite the steam deck install page to make it look nicer and to encourage `https://www.steamgriddb.com/boop`
