### ISSUE TITLE
Game unable to open.

### ISSUE THREAD

**Issue by Siena1762** [PrismLauncher/prismlauncher.org#509]
The other day i had downloaded some more mods for my 1.20.1 severs to enhance my gaming experience and yet when i tried to launch my game it proceeded to end with a code: 255. I have used this 1.20.1 sever the day before and it was fine, yet i do not understand what changed, i tried updating all of my mods, and got rid of some of the ones that i had downloaded the day before. Can someone please explain why it won't launch?
<img width="645" alt="Screenshot 2024-07-21 at 3 31 59 PM" src="https://github.com/user-attachments/assets/5b044024-13f1-4a49-b7fa-a0f97d996e80">

**Comment by Trial97** [comment]
It's not a prism issue.
If you want help use our discord: https://prismlauncher.org/discord
