### ISSUE TITLE
Logins code from pc to phone does not work

### ISSUE THREAD

**Issue by Kirbyzilla2024** [PrismLauncher/prismlauncher.org#584]
I would like to complain because every time I put in a code trying to login in the Prisma launcher it says 'it failed to login into this application so I hope you fix this issue BECAUSE I CAN'T MAKE An ACCOUNT until this problem is fixed.

**Comment by Trial97** [comment]
Duplicate of https://github.com/PrismLauncher/PrismLauncher/issues/2302 
Also this is no place for this kind of issues
