### ISSUE TITLE
Inconsistency: Logo is small icon version instead of full version with name on index page

### ISSUE THREAD

**Issue by SolDev69** [PrismLauncher/prismlauncher.org#99]
Might be intentional but [PolyMC's index page](https://polymc.org/) shows the full logo with the name "PolyMC" however [Prism's index page](https://prismlauncher.org/) only shows the small hexagonal prism icon.

**Comment by txtsd** [comment]
We need this! Currently it looks like `News` is part of the logo.

**Comment by Lutitious** [comment]
Done and it looks stylish imo

Dark Mode
![image](https://user-images.githubusercontent.com/25961265/197903177-eaa463a6-be51-4f0c-8421-5faa94c6339d.png)

Light Mode 
![image](https://user-images.githubusercontent.com/25961265/197903262-2f167d79-e586-48e3-8466-d5b9a6aebe62.png)

**Comment by SolDev69** [comment]
Aight I'ma close this then

**Comment by Lutitious** [comment]
i mean it still needs to be merged lol but yeah probably fine to close
